version: '3.8'

services:
    bot:
        build: ./
        restart: always
        command: python src/clean_architecture_app/main/bot.py
        env_file:
            - .env
        volumes:
            - ./src/clean_architecture_app/infrastructure/db/migrations/versions:/app/infrastructure/db/migrations/versions
        depends_on:
            - db
            - bot_redis

    migration:
        build: ./
        restart: on-failure
        env_file:
            - .env
        depends_on:
            - db
        command: [ "alembic", "upgrade", "head" ]

    bot_redis:
        image: redis:7.0.4-alpine
        restart: always
        ports:
            - "6379:6378"
        volumes:
            - redis_data:/data

    db:
        image: postgres:14.5-alpine
        restart: always
        env_file:
            - .env
        volumes:
            - db_data:/var/lib/postgresql/data/

volumes:
    db_data:
    redis_data: