version: '3.8'

services:
    bot_redis:
        container_name: redis
        image: redis:7.0.4-alpine
        restart: on-failure
        ports:
            - "6379:6378"
        volumes:
            - redis_data:/data

    db:
        container_name: db
        image: postgres:14.5-alpine
        restart: on-failure
        env_file:
            - .env
        volumes:
            - db_data:/var/lib/postgresql/data/

    migration:
        container_name: migration
        build: ./
        restart: on-failure
        env_file:
            - .env
        depends_on:
            - db
        command: [ "alembic", "upgrade", "head" ]

    bot:
        container_name: bot
        build: ./
        restart: on-failure
        command: python src/tactic/presentation/bot.py
        env_file:
            - .env
        volumes:
            - ./src/tactic/infrastructure/db/migrations/versions:/app/infrastructure/db/migrations/versions
        depends_on:
            - migration
            - bot_redis

volumes:
    db_data:
    redis_data: